language: node_js
node_js:
- '0.10'
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - "export CHROME_BIN=/usr/bin/chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install
  - bower install
before_script:
  - grunt shell --target=dev
notifications:
  email:
    recipients:
      - gregg@bitpay.com
    on_success: always
